from django.urls import path

from . import (
    views_admin,
    views_events,
    views_file_access,
    views_groups,
    views_history,
    views_requests,
    views_rules,
    views_sources,
)

app_name = "console"

urlpatterns = [
    path("events/", views_events.events, name="events"),
    path("events/updates/", views_events.event_updates, name="event_updates"),
    path("events/create-rules/", views_events.events_create_rules, name="events_create_rules"),
    path("events/resolve/", views_events.events_resolve, name="events_resolve"),
    path("events/<int:pk>/", views_events.event_detail, name="event"),
    path("events/<int:pk>/create-rule/", views_events.event_create_rule, name="event_create_rule"),

    path("rules/", views_rules.rules, name="rules"),
    path("rules/bulk/", views_rules.rules_bulk, name="rules_bulk"),
    path("rules/add/", views_rules.rule_form, name="rule_add"),
    path("rules/existing/", views_rules.rules_existing, name="rules_existing"),
    path("rules/export.csv", views_rules.rules_export, name="rules_export"),
    path("rules/upload/", views_rules.rule_upload, name="rule_upload"),
    path("rules/<int:pk>/", views_rules.rule_form, name="rule"),
    path("rules/<int:pk>/toggle/", views_rules.rule_toggle, name="rule_toggle"),
    path("rules/<int:pk>/delete/", views_rules.rule_delete, name="rule_delete"),

    path("packages/", views_sources.sources, name="sources"),
    path("packages/add/", views_sources.source_form, name="source_add"),
    path("packages/catalog/", views_sources.catalog_search, name="catalog_search"),
    path("packages/<int:pk>/", views_sources.source_detail, name="source"),
    path("packages/<int:pk>/edit/", views_sources.source_form, name="source_edit"),
    path("packages/<int:pk>/delete/", views_sources.source_delete, name="source_delete"),
    path("packages/<int:pk>/check/", views_sources.source_check, name="source_check"),
    path("packages/versions/<int:pk>/approve/", views_sources.version_set_enabled, {"enabled": True},
         name="version_approve"),
    path("packages/versions/<int:pk>/disable/", views_sources.version_set_enabled, {"enabled": False},
         name="version_disable"),

    path("file-access/", views_file_access.file_access_rules, name="file_access_rules"),
    path("file-access/add/", views_file_access.file_access_rule_form, name="file_access_rule_add"),
    path("file-access/<int:pk>/", views_file_access.file_access_rule_form, name="file_access_rule"),
    path("file-access/<int:pk>/delete/", views_file_access.file_access_rule_delete, name="file_access_rule_delete"),

    path("groups/", views_groups.groups, name="groups"),
    path("groups/add/", views_groups.group_form, name="group_add"),
    path("groups/base-profile/", views_groups.base_profile_download, name="base_profile"),
    path("groups/<int:pk>/", views_groups.group_form, name="group"),
    path("groups/<int:pk>/profile/", views_groups.group_profile_download, name="group_profile"),
    path("groups/<int:pk>/regenerate-token/", views_groups.group_regenerate_token, name="group_regenerate_token"),
    path("groups/<int:pk>/delete/", views_groups.group_delete, name="group_delete"),

    path("macs/", views_groups.machines, name="machines"),
    path("macs/<int:pk>/", views_groups.machine_detail, name="machine"),
    path("macs/<int:pk>/clean-sync/", views_groups.machine_clean_sync, name="machine_clean_sync"),
    path("macs/<int:pk>/rules/remove/", views_groups.machine_rules_remove, name="machine_rules_remove"),

    path("requests/", views_requests.admin_requests, name="requests"),
    path("requests/<int:pk>/", views_requests.admin_request_detail, name="request"),
    path("requests/<int:pk>/approve/", views_requests.admin_request_approve, name="request_approve"),
    path("requests/<int:pk>/deny/", views_requests.admin_request_deny, name="request_deny"),

    path("history/<str:model>/<int:pk>/", views_history.history, name="history"),

    path("administration/", views_admin.administration, name="administration"),
    path("administration/users/", views_admin.users, name="admin_users"),
    path("administration/users/add/", views_admin.user_form, name="admin_user_add"),
    path("administration/users/<int:pk>/", views_admin.user_form, name="admin_user"),
    path("administration/roles/", views_admin.roles, name="admin_roles"),
    path("administration/roles/add/", views_admin.role_form, name="admin_role_add"),
    path("administration/roles/<int:pk>/", views_admin.role_form, name="admin_role"),
    path("administration/roles/<int:pk>/delete/", views_admin.role_delete, name="admin_role_delete"),
    path("administration/sign-in-groups/", views_admin.sign_in_groups, name="admin_sign_in_groups"),
    path("administration/sign-in-groups/add/", views_admin.sign_in_group_form, name="admin_sign_in_group_add"),
    path("administration/sign-in-groups/<int:pk>/", views_admin.sign_in_group_form, name="admin_sign_in_group"),
    path("administration/sign-in-groups/<int:pk>/delete/", views_admin.sign_in_group_delete,
         name="admin_sign_in_group_delete"),
    path("administration/tags/", views_admin.tags, name="admin_tags"),
    path("administration/tags/add/", views_admin.tag_form, name="admin_tag_add"),
    path("administration/tags/<int:pk>/", views_admin.tag_form, name="admin_tag"),
    path("administration/tags/<int:pk>/delete/", views_admin.tag_delete, name="admin_tag_delete"),
    path("administration/configuration/", views_admin.config, name="admin_config"),
    path("administration/configuration/export/", views_admin.config_export, name="admin_config_export"),
    path("administration/configuration/import/", views_admin.config_import, name="admin_config_import"),
]
