# Generated by Django 6.0.8 on 2026-09-25 12:39

import django.db.models.deletion
import santa.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sync_token', models.CharField(default=santa.models.generate_sync_token, editable=False, help_text='Secret part of the sync URL. Regenerate it with the admin action if it leaks.', max_length=64, unique=True)),
                ('client_mode', models.CharField(choices=[('MONITOR', 'Monitor'), ('LOCKDOWN', 'Lockdown')], default='MONITOR', help_text='Monitor: everything runs except the blocked binaries, unknown binaries are logged as ALLOW_UNKNOWN events (use it to prepare the rules). Lockdown: only allowed binaries run, unknown ones are blocked (BLOCK_UNKNOWN).', max_length=16)),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='How many rules the Mac downloads per request during a sync (5 – 500).')),
                ('full_sync_interval', models.PositiveIntegerField(default=600, help_text='Seconds between two syncs of a Mac (min. 60). New rules arrive at the next sync.')),
                ('allowed_path_regex', models.TextField(blank=True, help_text='One regular expression per line, matched against the full path of the binary. Matching binaries are allowed, even in lockdown, without any rule. Anchor them (^/Applications/Foo\\.app/) and never use user-writable paths: anyone who can write there can run anything.', verbose_name='allowed path regexes')),
                ('blocked_path_regex', models.TextField(blank=True, help_text='One regular expression per line. Matching binaries are blocked, also in monitor mode, e.g. ^/Users/[^/]+/Downloads/', verbose_name='blocked path regexes')),
                ('enable_bundles', models.BooleanField(default=False, help_text='When a binary from an app bundle is blocked, Santa computes a hash of the whole bundle and adds it to the event. This server does not create bundle rules: allow apps with a Signing ID or Team ID rule instead. Leave it off unless you want the bundle hashes in the events.')),
                ('enable_transitive_rules', models.BooleanField(default=False, help_text='Files written by a binary with an “Allow compiler” rule (e.g. clang, swiftc, go) are allowed automatically on that Mac (transitive rules, local to the Mac). Needed by developers in lockdown to run what they build. Without “Allow compiler” rules this option does nothing.')),
                ('enable_all_event_upload', models.BooleanField(default=False, help_text='Upload an event for every execution, including the allowed ones, not only for the blocked / unknown ones. Useful to see what runs before switching a group to lockdown, but very noisy.')),
                ('block_usb_mount', models.BooleanField(default=False, help_text='Block the mounting of USB mass storage devices (sticks, external disks).', verbose_name='block USB mass storage')),
                ('remount_usb_mode', models.CharField(blank=True, help_text='Only with “Block USB mass storage”: instead of blocking, remount the device with these flags, comma separated, e.g. rdonly,noexec (read only, nothing executable). Allowed: -j, async, nobrowse, nodev, noexec, noowners, nosuid, rdonly.', max_length=200, verbose_name='remount USB with flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(help_text='Santa machine ID, the hardware UUID', max_length=64, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=64)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('model_identifier', models.CharField(blank=True, max_length=64)),
                ('os_version', models.CharField(blank=True, max_length=32)),
                ('os_build', models.CharField(blank=True, max_length=32)),
                ('santa_version', models.CharField(blank=True, max_length=64)),
                ('primary_user', models.CharField(blank=True, max_length=255)),
                ('client_mode', models.CharField(blank=True, choices=[('MONITOR', 'Monitor'), ('LOCKDOWN', 'Lockdown')], help_text='Mode reported by the client', max_length=16)),
                ('binary_rule_count', models.PositiveIntegerField(default=0)),
                ('certificate_rule_count', models.PositiveIntegerField(default=0)),
                ('teamid_rule_count', models.PositiveIntegerField(default=0)),
                ('signingid_rule_count', models.PositiveIntegerField(default=0)),
                ('cdhash_rule_count', models.PositiveIntegerField(default=0)),
                ('compiler_rule_count', models.PositiveIntegerField(default=0)),
                ('transitive_rule_count', models.PositiveIntegerField(default=0)),
                ('synced_rules', models.JSONField(blank=True, default=dict, editable=False)),
                ('pending_sync', models.JSONField(blank=True, editable=False, null=True)),
                ('clean_sync_requested', models.BooleanField(default=False, help_text='Send a clean sync (client drops all its rules) at the next preflight.')),
                ('sync_in_clean_mode', models.BooleanField(default=False, editable=False)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_preflight_at', models.DateTimeField(blank=True, null=True)),
                ('last_postflight_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='santa.group')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('GITHUB_RELEASE', 'GitHub release'), ('HOMEBREW_FORMULA', 'Homebrew formula (bottle)'), ('HOMEBREW_CASK', 'Homebrew cask'), ('URL', 'Direct download URL')], max_length=32)),
                ('identifier', models.CharField(help_text='GitHub: owner/repo (e.g. abiosoft/colima) · Homebrew: formula or cask name · URL: the full URL', max_length=500)),
                ('asset_pattern', models.CharField(blank=True, help_text='Regex. GitHub: matched against the asset names (e.g. Darwin). Homebrew formula: matched against the bottle tags (e.g. ^arm64_). Homebrew cask: matched against the download URLs. Empty = everything.', max_length=200)),
                ('binary_pattern', models.CharField(blank=True, help_text='Glob matched against the paths inside an archive (e.g. */bin/colima). Empty = every Mach-O executable found.', max_length=200)),
                ('include_prereleases', models.BooleanField(default=False, help_text='GitHub only')),
                ('is_global', models.BooleanField(default=False, help_text='Allow on every Mac')),
                ('auto_approve', models.BooleanField(default=True, help_text='Enable the rules of new releases right away. Otherwise they wait for approval.')),
                ('keep_versions', models.PositiveIntegerField(default=3, help_text='Rules of older versions are deleted. 0 = keep all.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='release_sources', to='santa.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('binary_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='santa.releasesource')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('BINARY', 'Binary (SHA-256)'), ('CERTIFICATE', 'Certificate (SHA-256)'), ('TEAMID', 'Team ID'), ('SIGNINGID', 'Signing ID'), ('CDHASH', 'CDHash')], default='BINARY', help_text='Binary: exactly this file, every new version needs a new rule (unsigned tools). CDHash: this code signature of the file. Signing ID: this program from this developer, all versions (best for signed apps). Certificate: everything signed with this certificate. Team ID: everything from this developer. The most specific rule type wins on the Mac: CDHash > Binary > Signing ID > Certificate > Team ID.', max_length=16)),
                ('identifier', models.CharField(help_text='SHA-256 for binaries / certificates, 10 character Team ID, TEAMID:bundle.id (or platform:bundle.id) for signing IDs, 40 character CDHash.', max_length=256)),
                ('policy', models.CharField(choices=[('ALLOWLIST', 'Allow'), ('ALLOWLIST_COMPILER', 'Allow compiler'), ('BLOCKLIST', 'Block'), ('SILENT_BLOCKLIST', 'Block silently'), ('CEL', 'CEL expression')], default='ALLOWLIST', help_text='Allow compiler: allowed, and the files it writes are allowed too on Macs with transitive rules enabled. Block silently: blocked without showing the dialog. CEL: allow or block depending on a CEL expression (e.g. on the arguments).', max_length=32)),
                ('custom_msg', models.CharField(blank=True, help_text='Shown in the block dialog', max_length=500, verbose_name='custom message')),
                ('custom_url', models.URLField(blank=True, help_text='Opened from the block dialog', max_length=800)),
                ('cel_expr', models.TextField(blank=True, verbose_name='CEL expression')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_global', models.BooleanField(default=False, help_text='Apply to every Mac')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled rules are removed from the Macs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='rules', to='santa.group')),
                ('machines', models.ManyToManyField(blank=True, help_text='Apply to these individual Macs', related_name='rules', to='santa.machine')),
                ('release_source', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='santa.releasesource')),
                ('release_version', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='santa.releaseversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(db_index=True, max_length=64)),
                ('execution_time', models.DateTimeField(db_index=True)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('executing_user', models.CharField(blank=True, max_length=255)),
                ('parent_name', models.CharField(blank=True, max_length=255)),
                ('bundle_id', models.CharField(blank=True, max_length=255)),
                ('bundle_name', models.CharField(blank=True, max_length=255)),
                ('bundle_version', models.CharField(blank=True, max_length=128)),
                ('signing_id', models.CharField(blank=True, max_length=255)),
                ('team_id', models.CharField(blank=True, max_length=32)),
                ('cdhash', models.CharField(blank=True, max_length=64)),
                ('cert_sha256', models.CharField(blank=True, max_length=64)),
                ('cert_cn', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='santa.group')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='santa.machine')),
                ('resolution_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to='santa.rule')),
            ],
            options={
                'ordering': ['-execution_time'],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['rule_type', 'identifier'], name='santa_rule_rule_ty_ffddb1_idx'),
        ),
    ]
