# Generated by Django 6.0.8 on 2026-09-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banned_block_message',
            field=models.TextField(blank=True, help_text="Profile only. Shown when a binary is blocked by a block rule. Empty = Santa's default text."),
        ),
        migrations.AddField(
            model_name='group',
            name='enable_bad_signature_protection',
            field=models.BooleanField(default=False, help_text='Profile only. Also block, in monitor mode, the binaries with a broken code signature (tampered files), unless a rule allows them.'),
        ),
        migrations.AddField(
            model_name='group',
            name='event_detail_text',
            field=models.CharField(blank=True, help_text='e.g. “Request access”. Sent at every sync.', max_length=48, verbose_name='block dialog button text'),
        ),
        migrations.AddField(
            model_name='group',
            name='event_detail_url',
            field=models.URLField(blank=True, help_text='Button in the block dialog, e.g. a ticket form of the IT. Santa replaces placeholders such as %file_sha%, %machine_id% and %username% (see the Santa docs). Sent at every sync.', max_length=800, verbose_name='block dialog URL'),
        ),
        migrations.AddField(
            model_name='group',
            name='unknown_block_message',
            field=models.TextField(blank=True, help_text="Profile only. Shown when an unknown binary is blocked in lockdown, e.g. how to ask for access. Empty = Santa's default text."),
        ),
        migrations.AlterField(
            model_name='group',
            name='batch_size',
            field=models.PositiveIntegerField(default=100, help_text='How many events the Mac uploads, and how many rules it downloads, per request (5 – 500).'),
        ),
    ]
