# Generated by Django 6.0.8 on 2026-09-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0002_group_block_dialog_and_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='releasesource',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Added to the rules of every new release', related_name='release_sources', to='santa.tag'),
        ),
        migrations.AddField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Only to sort and find the rules, no effect on the Macs', related_name='rules', to='santa.tag'),
        ),
    ]
