# Generated by Django 6.0.8 on 2026-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0003_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('SIGNINGID', 'Signing ID'), ('BINARY', 'Binary (SHA-256)'), ('TEAMID', 'Team ID'), ('CERTIFICATE', 'Certificate (SHA-256)'), ('CDHASH', 'CDHash')], default='SIGNINGID', help_text='Binary: exactly this file, every new version needs a new rule (unsigned tools). CDHash: this code signature of the file. Signing ID: this program from this developer, all versions (best for signed apps). Certificate: everything signed with this certificate. Team ID: everything from this developer. The most specific rule type wins on the Mac: CDHash > Binary > Signing ID > Certificate > Team ID.', max_length=16),
        ),
    ]
