# Generated by Django 6.0.8 on 2026-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0004_signing_id_default_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasesource',
            name='auto_approve_delay_days',
            field=models.PositiveIntegerField(default=0, help_text='With auto approve: enable the rules of a new release only this many days after it was published (GitHub), or first seen by this server (Homebrew, URL). Gives time to notice a compromised release. 0 = right away. “Enable / approve” on the rules skips the wait, disabling them cancels it.', verbose_name='auto approve delay (days)'),
        ),
        migrations.AddField(
            model_name='releaseversion',
            name='auto_enable_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='auto_approve',
            field=models.BooleanField(default=True, help_text='Enable the rules of new releases automatically. Otherwise they wait for approval.'),
        ),
    ]
