# Generated by Django 6.0.8 on 2026-09-28 08:04

from django.db import migrations, models


def set_version_identifiers(apps, schema_editor):
    # until now a source had a single identifier
    ReleaseSource = apps.get_model("santa", "ReleaseSource")
    ReleaseVersion = apps.get_model("santa", "ReleaseVersion")
    for source in ReleaseSource.objects.all():
        ReleaseVersion.objects.filter(source=source).update(identifier=source.identifier.strip()[:450])


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0005_release_auto_approve_delay'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='releaseversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='cel_expr',
            field=models.TextField(blank=True, help_text='Only with the CEL policy', verbose_name='CEL expression'),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='custom_msg',
            field=models.CharField(blank=True, help_text='Block and CEL: shown in the block dialog', max_length=500, verbose_name='custom message'),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='custom_url',
            field=models.URLField(blank=True, help_text='Block and CEL: opened from the block dialog', max_length=800),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='policy',
            field=models.CharField(choices=[('ALLOWLIST', 'Allow'), ('ALLOWLIST_COMPILER', 'Allow compiler'), ('BLOCKLIST', 'Block'), ('SILENT_BLOCKLIST', 'Block silently'), ('CEL', 'CEL expression')], default='ALLOWLIST', max_length=32),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='rule_type',
            field=models.CharField(choices=[('SIGNINGID', 'Signing ID'), ('BINARY', 'Binary (SHA-256)'), ('TEAMID', 'Team ID'), ('CERTIFICATE', 'Certificate (SHA-256)'), ('CDHASH', 'CDHash')], default='BINARY', help_text='The rules created for the executables found. Binary / CDHash: one rule per file and version. Signing ID / Certificate / Team ID: one rule for all versions, for signed tools. An executable without that information (unsigned) gets a Binary rule instead.', max_length=16, verbose_name='preferred rule type'),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='version_pattern',
            field=models.CharField(blank=True, help_text='Regex. Only releases whose version matches are taken (e.g. ^1\\. to stay on 1.x). Empty = every version.', max_length=200),
        ),
        migrations.AddField(
            model_name='releaseversion',
            name='identifier',
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.RunPython(set_version_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='releasesource',
            name='asset_pattern',
            field=models.CharField(blank=True, help_text='Regex. GitHub: matched against the asset names (e.g. Darwin). Homebrew formula: matched against the bottle tags (e.g. ^arm64_). Homebrew cask: matched against the download URLs. VS Code: matched against the target platforms (darwin-arm64, darwin-x64, universal). JetBrains: matched against the compatible products (e.g. ^PHPSTORM$). Empty = everything.', max_length=200),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='identifier',
            field=models.TextField(help_text='One per line, each one is checked on its own and keeps its own versions. GitHub: owner/repo (e.g. abiosoft/colima) · Homebrew: formula or cask name · URL: the full URL · npm: package name (e.g. @esbuild/darwin-arm64) · VS Code: publisher.name (e.g. rust-lang.rust-analyzer) · JetBrains: plugin ID (e.g. com.intellij.plugins.watcher)', verbose_name='identifiers'),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='include_prereleases',
            field=models.BooleanField(default=False, help_text='GitHub, VS Code, JetBrains (EAP)'),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='kind',
            field=models.CharField(choices=[('GITHUB_RELEASE', 'GitHub release'), ('HOMEBREW_FORMULA', 'Homebrew formula (bottle)'), ('HOMEBREW_CASK', 'Homebrew cask'), ('URL', 'Direct download URL'), ('NPM_PACKAGE', 'npm package'), ('VSCODE_EXTENSION', 'VS Code extension'), ('JETBRAINS_PLUGIN', 'JetBrains plugin (PhpStorm, …)')], max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='releaseversion',
            unique_together={('source', 'identifier', 'version')},
        ),
    ]
