# Generated by Django 6.0.8 on 2026-09-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0006_release_source_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='releasesource',
            name='identifier_icons',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EVENT', 'Blocked on my Mac'), ('PACKAGE', 'Package'), ('OTHER', 'Other')], max_length=16)),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('package_kind', models.CharField(blank=True, choices=[('GITHUB_RELEASE', 'GitHub release'), ('HOMEBREW_FORMULA', 'Homebrew formula (bottle)'), ('HOMEBREW_CASK', 'Homebrew cask'), ('URL', 'Direct download URL'), ('NPM_PACKAGE', 'npm package'), ('VSCODE_EXTENSION', 'VS Code extension'), ('JETBRAINS_PLUGIN', 'JetBrains plugin (PhpStorm, …)')], max_length=32)),
                ('package_identifier', models.CharField(blank=True, max_length=450)),
                ('title', models.CharField(max_length=200)),
                ('justification', models.TextField(max_length=1000)),
                ('link', models.URLField(blank=True, max_length=800)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='santa.event')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='santa.machine')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
                ('result_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='santa.rule')),
                ('result_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='santa.releasesource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
