# Generated by Django 6.0.8 on 2026-09-28 11:20

import django.db.models.deletion
from django.db import migrations, models


def copy_packages(apps, schema_editor):
    # until now a request had a single package
    AccessRequest = apps.get_model("santa", "AccessRequest")
    AccessRequestPackage = apps.get_model("santa", "AccessRequestPackage")
    status = {"APPROVED": "APPROVED", "DENIED": "DENIED"}
    for access_request in AccessRequest.objects.filter(kind="PACKAGE").exclude(package_identifier=""):
        AccessRequestPackage.objects.create(
            access_request=access_request, kind=access_request.package_kind,
            identifier=access_request.package_identifier,
            status=status.get(access_request.status, "PENDING"), result_source=access_request.result_source,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0007_icons_and_access_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GITHUB_RELEASE', 'GitHub release'), ('HOMEBREW_FORMULA', 'Homebrew formula (bottle)'), ('HOMEBREW_CASK', 'Homebrew cask'), ('URL', 'Direct download URL'), ('NPM_PACKAGE', 'npm package'), ('VSCODE_EXTENSION', 'VS Code extension'), ('JETBRAINS_PLUGIN', 'JetBrains plugin (PhpStorm, …)')], max_length=32)),
                ('identifier', models.CharField(max_length=450)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('icon_url', models.URLField(blank=True, max_length=800)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Not approved')], default='PENDING', max_length=16)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='santa.accessrequest')),
                ('result_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='santa.releasesource')),
            ],
            options={
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['kind', 'identifier'], name='santa_acces_kind_090357_idx')],
            },
        ),
        migrations.RunPython(copy_packages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='accessrequest',
            name='package_identifier',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='package_kind',
        ),
    ]
