# Generated by Django 6.0.8 on 2026-09-28 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0008_access_request_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('auto', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='auto', help_text='System: follows the light or dark mode of your computer.', max_length=8)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('de', 'Deutsch')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='santa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
