# Generated by Django 6.0.8 on 2026-09-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0009_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='event_detail_url',
            field=models.URLField(blank=True, help_text='Button in the block dialog, e.g. a ticket form of your IT team. Santa replaces placeholders such as %file_sha%, %machine_id% and %username% (see the Santa docs). Sent at every sync.', max_length=800, verbose_name='block dialog URL'),
        ),
    ]
