# Generated by Django 6.0.8 on 2026-09-29 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('santa', '0010_neutral_help_texts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at'], 'permissions': [('request_event', 'Can request the apps blocked on their Macs'), ('request_package', 'Can request packages'), ('request_other', 'Can request other software')]},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_admin_role',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='SignInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_value', models.CharField(help_text='The value in the groups claim of the ID token: the object ID or the name of the group, depending on the provider. * is everyone who signs in.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='A name to recognise the group, only for display', max_length=200)),
                ('console_access', models.BooleanField(default=False, help_text='The members can open the console (with the permissions of their roles)')),
                ('members', models.ManyToManyField(blank=True, editable=False, related_name='sign_in_groups', to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, help_text='The members get these roles', related_name='sign_in_groups', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
