# Generated by Django 6.0.8 on 2026-09-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0012_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
