# Generated by Django 6.0.8 on 2026-10-05 12:13

import santa.models
from django.db import migrations, models


def usb_to_removable_media(apps, schema_editor):
    # block_usb_mount with remount flags remounted, without flags it blocked (what Santa itself does with them)
    Group = apps.get_model("santa", "Group")
    for group in Group.objects.filter(block_usb_mount=True):
        flags = ",".join(flag.strip() for flag in group.remount_usb_mode.split(",") if flag.strip())
        group.removable_media_action = "REMOUNT" if flags else "BLOCK"
        group.removable_media_remount_flags = flags
        group.save(update_fields=["removable_media_action", "removable_media_remount_flags"])


def removable_media_to_usb(apps, schema_editor):
    Group = apps.get_model("santa", "Group")
    for group in Group.objects.exclude(removable_media_action="ALLOW"):
        group.block_usb_mount = True
        group.remount_usb_mode = group.removable_media_remount_flags if group.removable_media_action == "REMOUNT" else ""
        group.save(update_fields=["block_usb_mount", "remount_usb_mode"])


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0014_saved_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='branding_company_logo',
            field=models.TextField(blank=True, help_text='Profile only. Shown instead of the company name (84 × 28 points).', validators=[santa.models.validate_logo_url]),
        ),
        migrations.AddField(
            model_name='group',
            name='branding_company_logo_dark',
            field=models.TextField(blank=True, help_text='Profile only. The logo in dark mode. Empty = the logo above.', validators=[santa.models.validate_logo_url]),
        ),
        migrations.AddField(
            model_name='group',
            name='branding_company_name',
            field=models.CharField(blank=True, help_text='Profile only. Your company name in the dialogs and messages of Santa (Santa 2026.1 and newer).', max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='encrypted_removable_media_action',
            field=models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('REMOUNT', 'Remount with flags')], help_text='Encrypted disks (e.g. APFS encrypted) can get another action. Empty = the same as above. Santa 2026.1 and newer.', max_length=16, verbose_name='encrypted removable media'),
        ),
        migrations.AddField(
            model_name='group',
            name='encrypted_removable_media_remount_flags',
            field=models.CharField(blank=True, help_text='Only with “Remount with flags” for encrypted media. Comma separated, e.g. rdonly,noexec (read only, nothing executable). Allowed: -j, async, nobrowse, nodev, noexec, noowners, nosuid, rdonly.', max_length=200, verbose_name='remount flags of encrypted media'),
        ),
        migrations.AddField(
            model_name='group',
            name='on_start_usb_options',
            field=models.CharField(blank=True, choices=[('Unmount', 'Unmount'), ('ForceUnmount', 'Force unmount'), ('Remount', 'Remount'), ('ForceRemount', 'Force remount')], help_text='Profile only. What Santa does with the removable media already mounted when it starts, when they are blocked or remounted. Empty = leave them.', max_length=16, verbose_name='removable media mounted when Santa starts'),
        ),
        migrations.AddField(
            model_name='group',
            name='removable_media_action',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('REMOUNT', 'Remount with flags')], default='ALLOW', help_text='USB sticks, external disks, SD cards: allow them, block them, or remount them with the flags below (e.g. read only). Sent at every sync.', max_length=16, verbose_name='removable media'),
        ),
        migrations.AddField(
            model_name='group',
            name='removable_media_remount_flags',
            field=models.CharField(blank=True, help_text='Only with “Remount with flags”. Comma separated, e.g. rdonly,noexec (read only, nothing executable). Allowed: -j, async, nobrowse, nodev, noexec, noowners, nosuid, rdonly.', max_length=200, verbose_name='remount flags'),
        ),
        migrations.RunPython(usb_to_removable_media, removable_media_to_usb),
        migrations.RemoveField(
            model_name='group',
            name='block_usb_mount',
        ),
        migrations.RemoveField(
            model_name='group',
            name='remount_usb_mode',
        ),
    ]
