# Generated by Django 6.0.8 on 2026-10-05 13:14

import django.core.validators
import django.db.models.deletion
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def grant_to_admins(apps, schema_editor):
    # the permissions are only created after the migrations (post_migrate), the admins need them now
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None
    AuthGroup = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    admins = AuthGroup.objects.filter(name="Santa admins").first()
    if admins:
        admins.permissions.add(*Permission.objects.filter(
            content_type__app_label="santa", content_type__model__in=["fileaccessrule", "fileaccessprocess"]))



class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0015_removable_media_and_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='file_access_block_message',
            field=models.TextField(blank=True, help_text="Profile only. Shown when a file access rule blocks, unless the rule has its own message. Empty = Santa's default text."),
        ),
        migrations.AddField(
            model_name='group',
            name='override_file_access_action',
            field=models.CharField(choices=[('NONE', 'None, the rules apply'), ('AUDIT_ONLY', 'Audit only'), ('DISABLE', 'Disabled')], default='NONE', help_text='Overrides every file access rule of the group, e.g. to switch them off for a moment: “Audit only” logs instead of blocking, “Disabled” turns them off. Sent at every sync.', max_length=16, verbose_name='file access override'),
        ),
        migrations.CreateModel(
            name='FileAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shown in the logs and in the block dialog, e.g. SSH-keys. Letters, digits and . _ : - (no spaces).', max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('PathsWithAllowedProcesses', 'Paths: only the listed processes may access them'), ('PathsWithDeniedProcesses', 'Paths: the listed processes may not access them'), ('ProcessesWithAllowedPaths', 'Processes: may only access the listed paths'), ('ProcessesWithDeniedPaths', 'Processes: may not access the listed paths')], default='PathsWithAllowedProcesses', max_length=32)),
                ('paths', models.TextField(blank=True, help_text="One path per line, e.g. /Users/*/.ssh/id_rsa. Glob patterns (* ? [ ]) work, ** doesn't.")),
                ('path_prefixes', models.TextField(blank=True, help_text='One path per line: the path and everything below it, e.g. /Users/*/Library/Cookies/')),
                ('allow_read_access', models.BooleanField(default=False, help_text='Only writes are checked, everyone may read.')),
                ('audit_only', models.BooleanField(default=True, help_text="Only log the access, don't block it. Start with it, check the events, then turn it off.")),
                ('block_message', models.TextField(blank=True, help_text="Shown when the rule blocks. Empty = the message of the group, or Santa's default text.", validators=[django.core.validators.MaxLengthValidator(2048)])),
                ('event_detail_url', models.URLField(blank=True, max_length=800, verbose_name='block dialog URL')),
                ('event_detail_text', models.CharField(blank=True, max_length=48, verbose_name='block dialog button text')),
                ('enable_silent_mode', models.BooleanField(default=False, help_text='Block without the dialog.')),
                ('enable_silent_tty_mode', models.BooleanField(default=False, help_text='Block without the message in the terminal.')),
                ('is_global', models.BooleanField(default=False, verbose_name='all groups')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='file_access_rules', to='santa.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_id', models.CharField(blank=True, help_text='e.g. com.apple.ssh-agent, with the Team ID or “Platform binary”', max_length=300, verbose_name='signing ID')),
                ('team_id', models.CharField(blank=True, max_length=10, verbose_name='team ID')),
                ('platform_binary', models.BooleanField(default=False, help_text='Part of macOS')),
                ('binary_path', models.CharField(blank=True, max_length=1024)),
                ('cdhash', models.CharField(blank=True, max_length=40, verbose_name='CDHash')),
                ('certificate_sha256', models.CharField(blank=True, max_length=64, verbose_name='certificate SHA-256')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='santa.fileaccessrule')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(grant_to_admins, migrations.RunPython.noop),
    ]
