# Generated by Django 6.0.8 on 2026-10-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0016_file_access_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
