# Generated by Django 6.0.9 on 2026-10-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0017_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingroup',
            name='no_email',
            field=models.BooleanField(default=False, help_text='The members get no e-mail notifications, e.g. admin accounts without a mailbox. A user can be excepted in Administration → Users.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_override',
            field=models.CharField(blank=True, choices=[('', 'As the sign-in groups say'), ('off', 'No e-mails'), ('on', 'E-mails allowed')], default='', editable=False, max_length=8),
        ),
    ]
