# Generated by Django 6.0.9 on 2026-10-07 07:32

from django.db import migrations, models

# the defaults of notifications.NOTIFICATIONS at this migration
DEFAULTS = {"my_requests": "instant", "new_requests": "instant", "package_pending": "instant",
            "package_auto": "off", "package_errors": "instant"}


def forget_default_choices(apps, schema_editor):
    # The profile stored every choice it showed, also the untouched defaults. Those are no choice: without them,
    # the defaults of the sign-in groups apply.
    UserProfile = apps.get_model("santa", "UserProfile")
    for profile in UserProfile.objects.only("notifications").iterator():
        chosen = {key: value for key, value in profile.notifications.items() if DEFAULTS.get(key) != value}
        if chosen != profile.notifications:
            profile.notifications = chosen
            profile.save(update_fields=["notifications"])


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0018_email_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingroup',
            name='notification_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forget_default_choices, migrations.RunPython.noop),
    ]
