# Generated by Django 6.0.9 on 2026-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0019_sign_in_group_notification_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='inherit_file_access_rules',
            field=models.BooleanField(default=True, help_text='The file access rules of the parent group are also in the profile of this group.'),
        ),
        migrations.AddField(
            model_name='group',
            name='inherit_rules',
            field=models.BooleanField(default=True, help_text='The rules of the parent group also apply to the Macs of this group.'),
        ),
        migrations.AddField(
            model_name='group',
            name='overridden_settings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The group takes the settings of this group, except the ones it sets itself, and, if chosen below, its rules and file access rules. Its own rules win over the inherited ones.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='santa.group'),
        ),
    ]
