# Generated by Django 6.0.9 on 2026-10-07 10:04

import santa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0020_group_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='branding_company_logo',
            field=models.TextField(blank=True, help_text="Profile only. Shown instead of the company name: with a logo, Santa doesn't show the name (84 × 28 points).", validators=[santa.models.validate_logo_url]),
        ),
        migrations.AlterField(
            model_name='group',
            name='branding_company_name',
            field=models.CharField(blank=True, help_text='Profile only. Your company name in the dialogs and messages of Santa, only when no company logo is set (Santa 2026.1 and newer).', max_length=200),
        ),
    ]
