# Generated by Django 6.0.9 on 2026-10-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0021_branding_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasesource',
            name='approve_kept_versions',
            field=models.BooleanField(default=False, help_text='Also add the rules of the older versions inside the kept range, not only of the new ones (GitHub, npm, JetBrains). Not with 0 (keep all): that would allow every version ever published.', verbose_name='also allow the older kept versions'),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='include_dependencies',
            field=models.BooleanField(default=False, help_text='Also allow the executables of the dependencies of every new version, also indirect ones (npm: dependencies and optional dependencies for macOS; Homebrew formula: the runtime dependencies). Their rules belong to the version and are deleted with it.', verbose_name='allow the dependencies'),
        ),
        migrations.AddField(
            model_name='releasesource',
            name='keep_unit',
            field=models.CharField(choices=[('VERSIONS', 'versions'), ('WEEKS', 'weeks'), ('MONTHS', 'months')], default='VERSIONS', max_length=8),
        ),
        migrations.AddField(
            model_name='rule',
            name='release_dependency',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='keep_versions',
            field=models.PositiveIntegerField(default=3, help_text='The last versions, or the versions of the last weeks or months, keep their rules. The rules of older versions are deleted, the newest version always stays. 0 = keep all.', verbose_name='keep'),
        ),
    ]
