# Generated by Django 6.0.9 on 2026-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0022_release_keep_window_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseversion',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='releaseversion',
            name='dependencies_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='releasesource',
            name='approve_kept_versions',
            field=models.BooleanField(default=False, help_text='Also add the rules of the older versions inside the kept range, not only of the new ones (not for Homebrew casks and URLs). Not with 0 (keep all): that would allow every version ever published.', verbose_name='also allow the older kept versions'),
        ),
    ]
