# Generated by Django 6.0.9 on 2026-10-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0023_release_version_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseversion',
            name='dependency_binary_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
